<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.ViewModels\Core.ViewModels.csproj" />
    <ProjectReference Include="..\Feature.ViewObjects\Feature.ViewObjects.csproj" />
  </ItemGroup>

</Project>
